### ISSUE TITLE
`read` syscall shenanigans.

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/oc-cynosure-2#27]
This all began when I was trying to implement `cat` and reading a file using `"r"` mode seem to spam a bunch of newlines. I played around with different methods of reading a file and found out than reading more data than there are available seem to cause it to be filled with *something*.

```lua
repeat
    local chunk = syscall("read", fd, len)
    syscall("write", 1, chunk or "")
until not chunk
```

Setting `len` to 1, 2 and 4 works perfectly albeit super slow.
![Screenshot-2022-03-06,21-11-12](https://user-images.githubusercontent.com/25323231/156926912-880e501a-ed81-4027-8cfe-97ed0adb548b.png)

8 is where things start to get funky
![Screenshot-2022-03-06,21-13-55](https://user-images.githubusercontent.com/25323231/156926997-46ed4643-7902-4343-9f3a-9edd91101417.png)

**Comment by Ocawesome101** [comment]
from my debug logs:
```
[--vm--] [00004.15] read(--!lua

local args = ...

local function syscall(s, ...)
  return coroutine.yield("syscall", s, ...)
end

if #args == 0 then
  syscall("write", 2, "failed: argument needed\n")
  syscall("exit", 1)
end

local fd, err = syscall("open", args[1], "r")
if not fd then
  syscall("write", 2, "failed: " .. tostring(err) .. "\n")
  syscall("exit", 1)
end

local data = syscall("read", fd, "a")
syscall("close", fd)

syscall("write", 1, data)
)
[--vm--] [00004.18] read(nil)
```

so it's reading correctly.  this may be an issue with the TTY driver.

the following program indeed does not work:
```
--!lua
-- print many things

coroutine.yield("syscall", "write", 1, [[
   
Hi!

This is a friendly little test program.

It tests what happens when a lot of lines get written
to Cynosure's TTY in a big block.

Either it'll horribly break, or it will work fine.

I'm not sure which.
   
]])
```
which does pinpoint the problem as being the TTY driver and not the `read` syscall itself as one might initially suspect.

probing a bit further, this seems to be an issue when a string contains more than one newline - only the first line of text gets displayed.  it's not an issue with `tty:write` - so i think `internalwrite()` is the culprit here, with cursor toggling possibly playing a role.

**Comment by Ocawesome101** [comment]
turns out the issue was actually just that `textwrite()` wasn't calling `corral(self)` when it should have been.  adding a call to `corral` at the beginning of the function fixed the issue.
