### ISSUE TITLE
Use something other than `checkArg` for syscalls

### ISSUE THREAD

**Issue by atirutw** [oc-ulos/oc-cynosure-2#31]
Discovered the downsides myself when I forgot to provide the arguments table to `execve`. Could not even know what went wrong unless I enable the debug logs on line 38 and 39 in `src/syscall.lua`.

**Comment by Ocawesome101** [comment]
when a system call fails, it returns the error as its second result. this should probably be handled in a userspace `syscall` wrapper, which can e.g. print to `stderr` and exit if the returned error is a string.  otherwise the error should be handled by the calling process as with Linux systems.

unfortunately i don't think there's a much cleaner way to do this because Lua doesn't have compile-time argument checking, and  i do _not_ want the kernel to do stderr printing for userland processes if it is at all possible to avoid.  best case you can use a smart enough linter on your code and it'll yell at you.
